import { Inter } from 'next/font/google';
import './globals.css';
import WhatsAppButton from '@/components/Whatsapp';
import Link from 'next/link';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Ved Model International',
  // description: 'Generated by create next app',
  icons:{
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  }
};

export default function RootLayout({ children }) {

  
  
  return (
    <html lang="en">
      <Head>
        {/* Include your favicon */}
        <link rel="icon" href="/favicon.ico" />
          {/* Additional meta tags, stylesheets, etc. can be added here */}
      </Head>
      <body className={inter.className}>
        
        {children}
        {/* Render WhatsAppButton on all pages */}
        <WhatsAppButton />
      </body>
    </html>
  );
}
